### ISSUE TITLE
Предложение о добавлении параметра учета ширины окна в функцию SpringFonBegining()

### ISSUE THREAD

**Issue by LFionina** [AbraCobra/Cartoon_Chuck_journey#1]
В функции SpringFonBegining() параметры окна фиксированы, и чтобы эту функцию можно было бы использовать в других окна (например, которые шире) можно вместо числа 1100 добавить команду **txGetExtentX()**

Тогда ваша функция будет выглядеть вот так:

```
void SpringFonBegining()
    {
    txSetColor     (RGB (204, 255, 255));
    txSetFillColor (RGB (204, 255, 255));

    POINT sky[6] = {{0, 450}, {0, 350}, {600, 350}, {750, 350}, {txGetExtentX(), 350}, {txGetExtentX(), 430}};
    txPolygon (sky, 6);

    for (int gradSky = 1; gradSky < 200; gradSky++)
        {
        txSetColor     (RGB (204 - 2*gradSky, 255, 255));
        txSetFillColor (RGB (204 - 2*gradSky, 255, 255));

        POINT heaven[4] = {{             0, 350 - 4*gradSky}, {             0, 360 - 4*gradSky},
                           {txGetExtentX(), 360 - 4*gradSky}, {txGetExtentX(), 350 - 4*gradSky}};
        txPolygon (heaven, 4);
        }

    txSetColor     (RGB (51, 204, 51));
    txSetFillColor (RGB (51, 204, 51));

    POINT hillbegin[4] = {{0, 400}, {0, 900}, {txGetExtentX(), 900}, {txGetExtentX(), 400}};
    txPolygon (hillbegin, 4);
    }
```

**Comment by AbraCobra** [comment]
Ок! Попробую как доберусь до компа.

  
>Суббота, 22 мая 2021, 17:57 +03:00 от LFionina ***@***.***>:
> 
> 
>В функции SpringFonBegining() параметры окна фиксированы, и чтобы эту функцию можно было бы использовать в других окна (например, которые шире) можно вместо числа 1100 добавить команду  txGetExtentX()
>Тогда ваша функция будет выглядеть вот так:
>void SpringFonBegining()
>
>    {
>
>    txSetColor     (RGB (204, 255, 255));
>
>    txSetFillColor (RGB (204, 255, 255));
>
>
>
>    POINT sky[6] = {{0, 450}, {0, 350}, {600, 350}, {750, 350}, {txGetExtentX(), 350}, {txGetExtentX(), 430}};
>
>    txPolygon (sky, 6);
>
>
>
>    for (int gradSky = 1; gradSky < 200; gradSky++)
>
>        {
>
>        txSetColor     (RGB (204 - 2*gradSky, 255, 255));
>
>        txSetFillColor (RGB (204 - 2*gradSky, 255, 255));
>
>
>
>        POINT heaven[4] = {{             0, 350 - 4*gradSky}, {             0, 360 - 4*gradSky},
>
>                           {txGetExtentX(), 360 - 4*gradSky}, {txGetExtentX(), 350 - 4*gradSky}};
>
>        txPolygon (heaven, 4);
>
>        }
>
>
>
>    txSetColor     (RGB (51, 204, 51));
>
>    txSetFillColor (RGB (51, 204, 51));
>
>
>
>    POINT hillbegin[4] = {{0, 400}, {0, 900}, {txGetExtentX(), 900}, {txGetExtentX(), 400}};
>
>    txPolygon (hillbegin, 4);
>
>    }
>
>
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Ирина Абрамова

**Comment by AbraCobra** [comment]
Спасибо! Сделала. Скоро залью новую версию.
